apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bibbunited-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kerryhatcher/bibbunited.com.git
    targetRevision: main
    path: argocd/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: civpulse-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
