import { getPayload } from 'payload'
import config from '@payload-config'

async function seed() {
  const payload = await getPayload({ config })

  console.log('Seeding database...')

  // 1. Create or find a user (required as author for news posts)
  let user
  const existingUsers = await payload.find({
    collection: 'users',
    limit: 1,
    overrideAccess: true,
  })
  if (existingUsers.docs.length > 0) {
    user = existingUsers.docs[0]
    console.log('Using existing user:', user.email)
  } else {
    user = await payload.create({
      collection: 'users',
      data: {
        email: 'editor@bibbunited.com',
        password: 'seed-password-change-me',
      },
      overrideAccess: true,
    })
    console.log('Created user:', user.email)
  }

  // 2. Create a placeholder media item using sharp to generate a test image
  // Check if seed media already exists
  const existingMedia = await payload.find({
    collection: 'media',
    where: { alt: { equals: 'BIBB United test image for seed data' } },
    limit: 1,
    overrideAccess: true,
  })

  let media
  if (existingMedia.docs.length > 0) {
    media = existingMedia.docs[0]
    console.log('Using existing media:', media.id)
  } else {
    const { default: sharp } = await import('sharp')
    const imageBuffer = await sharp({
      create: {
        width: 1200,
        height: 630,
        channels: 3,
        background: { r: 30, g: 41, b: 59 },
      },
    })
      .jpeg()
      .toBuffer()

    media = await payload.create({
      collection: 'media',
      data: {
        alt: 'BIBB United test image for seed data',
      },
      file: {
        data: imageBuffer,
        name: 'seed-test-image.jpg',
        mimetype: 'image/jpeg',
        size: imageBuffer.length,
      },
      overrideAccess: true,
    })
    console.log('Created media:', media.id)
  }

  // 3. Create Pages (including one with title 'About' so slug auto-generates to 'about')
  // The slug field hook auto-generates from title on create, so we don't provide explicit slugs.
  // cms-page.spec.ts navigates to /about, so title 'About' => slug 'about' is critical.
  // Lexical rich text minimal structure
  const makeRichText = (text: string) => ({
    root: {
      type: 'root',
      children: [
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text,
              version: 1,
            },
          ],
          direction: 'ltr' as const,
          format: '' as const,
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr' as const,
      format: '' as const,
      indent: 0,
      version: 1,
    },
  })

  const pages = [
    {
      title: 'About',
      content: makeRichText(
        'BIBB United is a civic advocacy organization dedicated to transparency and accountability in the BIBB County School District. We believe every community member deserves clear, accessible information about how their schools are governed.',
      ),
    },
    {
      title: 'Get Involved',
      content: makeRichText(
        'Your voice matters in shaping the future of BIBB County schools. Attend board meetings, contact officials, and stay informed about the decisions that affect our children.',
      ),
    },
    {
      title: 'Resources',
      content: makeRichText(
        'Find links to official board documents, budget reports, and meeting minutes. Stay informed with primary sources.',
      ),
    },
  ]

  for (const pageData of pages) {
    // Check by title since slug is auto-generated by hook
    const existing = await payload.find({
      collection: 'pages',
      where: { title: { equals: pageData.title } },
      limit: 1,
      overrideAccess: true,
    })
    if (existing.docs.length === 0) {
      const created = await payload.create({
        collection: 'pages',
        data: {
          ...pageData,
          _status: 'published',
        },
        overrideAccess: true,
      })
      console.log('Created page:', created.slug)
    } else {
      console.log('Page already exists:', existing.docs[0].slug)
    }
  }

  // 4. Create NewsPosts (with author, featuredImage, published status)
  // Slugs are auto-generated from title by the hook
  const newsPosts = [
    {
      title: 'School Board Approves 2026-2027 Budget',
      publishDate: new Date('2026-03-15').toISOString(),
      body: makeRichText(
        'The BIBB County Board of Education voted 5-2 to approve the $180 million operating budget for the 2026-2027 school year. Key allocations include increased funding for teacher retention bonuses and facility maintenance.',
      ),
    },
    {
      title: 'Community Forum on School Safety Draws Record Attendance',
      publishDate: new Date('2026-03-10').toISOString(),
      body: makeRichText(
        'Over 300 community members packed the Central High School auditorium for a forum on school safety improvements. Parents, teachers, and students shared perspectives on proposed security upgrades and mental health resources.',
      ),
    },
    {
      title: 'New Superintendent Search Committee Formed',
      publishDate: new Date('2026-03-01').toISOString(),
      body: makeRichText(
        'The Board of Education has appointed a seven-member search committee to find the next superintendent of BIBB County Schools. The committee includes two parents, two teachers, one principal, and two community members.',
      ),
    },
  ]

  for (const postData of newsPosts) {
    // Check by title since slug is auto-generated by hook
    const existing = await payload.find({
      collection: 'news-posts',
      where: { title: { equals: postData.title } },
      limit: 1,
      overrideAccess: true,
    })
    if (existing.docs.length === 0) {
      const created = await payload.create({
        collection: 'news-posts',
        data: {
          ...postData,
          author: user.id,
          featuredImage: media.id,
          _status: 'published',
        },
        overrideAccess: true,
      })
      console.log('Created news post:', created.slug)
    } else {
      console.log('News post already exists:', existing.docs[0].slug)
    }
  }

  console.log('Seeding complete!')
  process.exit(0)
}

seed().catch((err) => {
  console.error('Seed error:', err)
  process.exit(1)
})
